theme: jekyll-theme-slate
title: Erik Thorsell
description: An online portfolio mixed up with thoughts.

social:
  - title: linkedin
    url: https://linkedin.com/in/thorsellerik
    logo: /logos/linkedin.png
  - title: twitter
    url: https://twitter.com/erikthorsell
    logo: /logos/twitter.png
  - title: github
    url: https://github.com/erikthorsell
    logo: /logos/github.png
  - title: email
    url: mailto:erik@thorsell.cc
    logo: /logos/email.png

